export const Images = {
  pricingIllustration1: require('./pricing_illustration1.png'),
  pricingIllustration2: require('./pricing_illustration2.png'),
  crossIcon: require('./cross_icon.png'),
  sessionHistory: require('./sessionHistory.png'),
  flower: require('./flower.png'),
  sandWatch: require('./sandwatch.png'),
  calendarIcon: require('./calendar.png'),
  whatsappIcon: require('./whatsappIcon.png'),
  questionIcon: require('./questionIcon.png'),
  emailIcon: require('./emailIcon.png'),
  rightIcon: require('./Right.png'),
  energizedIcon: require('./EnergizedIcon.png'),
  relaxedIcon: require('./RelaxedIcon.png'),
  strongIcon: require('./StrongIcon.png'),
  tiredIcon: require('./TiredIcon.png'),
  starIcon: require('./starIcon.png'),
};
